### ISSUE TITLE
Button label inconsistency

### ISSUE THREAD

**Issue by codified45** [learn-co-curriculum/phase-1-practice-interacting-with-the-dom#5]
### Canvas Link

https://learning.flatironschool.com/courses/6190/assignments/225624?module_item_id=526914#:~:text=Click%20the%20%22restart%22%20button%20to%20restart%20the%20counter%20and%20re%2Denable%20the%20buttons.

### Concern

Text reads:

> • switch the label on the button from "pause" to "resume"
> • Click the "restart" button to restart the counter and re-enable the buttons.  

Was this meant to say the "resume" button?  
Since the demo program doesn't have a "restart" button, are you requesting that we build an additional button that is not present in the example program?  The intention is unclear.

**Comment by DavidWolff218** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved.
Note, however, that if you are working in Canvas the changes may not show up
there, but they will for future students.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
